# Generated by Django 5.2.5 on 2025-08-09 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_phishlet_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_port', models.PositiveIntegerField(default=53, help_text='DNS server port (1-65535)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DNS Settings',
                'verbose_name_plural': 'DNS Settings',
            },
        ),
    ]
