# Generated by Django 5.2.5 on 2025-08-09 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dnssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='Fully-qualified domain name or subdomain (e.g. example.com, api.example.com)', max_length=253, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy Domain',
                'verbose_name_plural': 'Proxy Domains',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='DomainCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_pem', models.TextField(help_text='PEM encoded certificate (including chain if needed)')),
                ('key_pem', models.TextField(help_text='PEM encoded private key')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='core.proxydomain')),
            ],
            options={
                'verbose_name': 'Domain Certificate',
                'verbose_name_plural': 'Domain Certificates',
            },
        ),
    ]
