# Generated by Django 5.2.5 on 2025-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_captured',
            field=models.BooleanField(default=False, help_text='Whether any data has been captured (credentials, cookies, or custom data)'),
        ),
    ]
