# Generated by Django 5.2.5 on 2025-08-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_session_is_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishlet',
            name='proxy_auth',
            field=models.CharField(blank=True, help_text='Random URL path for proxy authentication', max_length=255),
        ),
    ]
