# Generated by Django 5.2.5 on 2025-08-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_phishlet_proxy_auth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('session_cookie', 'phishlet')},
        ),
    ]
