# Generated by Django 5.2.5 on 2025-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_session_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_proxy_auth',
            field=models.BooleanField(default=False, help_text='Whether this session was created through proxy authentication path'),
        ),
    ]
