# Generated by Django 5.2.5 on 2025-08-14 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_session_is_proxy_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the proxy', max_length=100)),
                ('proxy_type', models.CharField(choices=[('http', 'HTTP Proxy'), ('https', 'HTTPS Proxy'), ('socks4', 'SOCKS4 Proxy'), ('socks5', 'SOCKS5 Proxy')], default='http', help_text='Type of proxy', max_length=10)),
                ('host', models.CharField(help_text='Proxy hostname or IP address', max_length=255)),
                ('port', models.PositiveIntegerField(help_text='Proxy port number')),
                ('username', models.CharField(blank=True, help_text='Proxy authentication username (optional)', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Proxy authentication password (optional)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this proxy is active and available')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='phishlet',
            name='proxy',
            field=models.ForeignKey(blank=True, help_text='Proxy to use for this phishlet (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phishlets', to='core.proxy'),
        ),
    ]
