# Generated by Django 5.2.5 on 2025-08-14 17:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_dnssettings_id_alter_domaincertificate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Telegram bot token for notifications', max_length=255)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Telegram chat ID to send notifications to', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether notifications are enabled')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
