# Generated by Django 5.2.5 on 2025-08-22 07:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_phishlet_is_cache_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirectors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique identifier, used as filename.', max_length=150, unique=True)),
                ('data', models.TextField(help_text='HTML code for the redirector')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
