# Generated by Django 5.2.5 on 2025-08-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_redirectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishlet',
            name='redirector',
            field=models.ForeignKey(blank=True, help_text='if redirector is on it will be used as landing page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirectors', to='core.redirectors'),
        ),
    ]
